# Generated by Django 6.0.2 on 2026-02-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='steamgame',
            name='has_drm',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
