# Generated by Django 6.0.3 on 2026-03-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0002_steamgame_has_drm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamgame',
            name='type',
        ),
    ]
